/**
 * Preset provider configurations for quick channel setup.
 * Data extracted from cc-switch (reference/cc-switch) and adapted for ModelSwitch.
 */

export type PresetCategory =
  | "official"
  | "cn_official"
  | "aggregator"
  | "cloud_provider"
  | "third_party";

export type ApiFormat = "openai" | "anthropic" | "gemini";

export interface TemplateValueConfig {
  label: string;
  placeholder: string;
  defaultValue?: string;
  editorValue: string;
}

export interface ProviderPreset {
  name: string;
  category: PresetCategory;
  /** Maps to Provider enum in backend: openai | anthropic | deepseek | gemini | openrouter | custom */
  provider: string;
  baseUrl: string;
  defaultModel: string;
  /** Model name aliases: requested model → actual upstream model */
  modelMapping: Record<string, string>;
  /** Suggested priority: 1=free/subscription, 2=economy API, 3=official */
  priority: number;
  iconColor: string;
  /** URL where user can obtain an API key */
  apiKeyUrl?: string;
  /** Available models for this provider (for model selector UI) */
  models: string[];
  /** API protocol: determines which proxy route handles the channel */
  apiFormat?: ApiFormat;
  /** Alternate endpoint URLs for other API formats. Key is the apiFormat value. */
  endpoints?: Partial<Record<ApiFormat, string>>;
  /** Quota monitoring strategy: how to check balance/usage for this provider */
  quotaStrategy?: "http_api" | "openai_compat" | "webview" | "response_header" | "disabled";
  /** Custom billing endpoint override (only for http_api strategy) */
  quotaEndpoint?: string;
  /** Provider's official website URL */
  websiteUrl?: string;
  /** Alternate base URLs for speed-test / switch later */
  endpointCandidates?: string[];
  /** Exact override for model list fetch (e.g. /models or /v1/models) */
  modelsUrl?: string;
  /** Brand icon name (in addition to iconColor) */
  icon?: string;
  /** Template variables for placeholders like ${AWS_REGION} or ${ENDPOINT_ID} */
  templateValues?: Record<string, TemplateValueConfig>;
}


export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ─── Official ───
  {
    name: "Anthropic",
    category: "official",
    provider: "anthropic",
    baseUrl: "https://api.anthropic.com",
    defaultModel: "claude-sonnet-4-20250514",
    modelMapping: {},
    priority: 3,
    iconColor: "#D97757",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    apiFormat: "anthropic",
    quotaStrategy: "webview", // console.anthropic.com/api/oauth/usage
  },
  {
    name: "OpenAI",
    category: "official",
    provider: "openai",
    baseUrl: "https://api.openai.com",
    defaultModel: "gpt-4o",
    modelMapping: {},
    priority: 3,
    iconColor: "#00A67E",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    models: ["gpt-4o", "gpt-4o-mini", "o3", "o3-mini", "o4-mini"],
    quotaStrategy: "response_header",
  },

  // ─── CN Domestic ───
  {
    name: "DeepSeek",
    category: "cn_official",
    provider: "deepseek",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-v4-pro",
    modelMapping: {
      "gpt-4o": "deepseek-v4-pro",
      "gpt-4": "deepseek-v4-pro",
      "claude-3-sonnet": "deepseek-v4-pro",
    },
    priority: 2,
    iconColor: "#1E88E5",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    models: ["deepseek-v4-pro", "deepseek-v4-flash"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://api.deepseek.com",
      anthropic: "https://api.deepseek.com/anthropic",
    },
    websiteUrl: "https://platform.deepseek.com",
    modelsUrl: "https://api.deepseek.com/models",
    icon: "deepseek",
  },
  {
    name: "Zhipu GLM",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-5.1",
    modelMapping: {
      "gpt-4o": "glm-5.1",
      "gpt-4": "glm-5.1",
    },
    priority: 2,
    iconColor: "#0F62FE",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code",
    models: ["glm-5.1", "glm-5"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://open.bigmodel.cn/api/paas/v4",
      anthropic: "https://open.bigmodel.cn/api/anthropic",
    },
    websiteUrl: "https://open.bigmodel.cn",
    icon: "zhipu",
  },
  {
    name: "Zhipu GLM en",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.z.ai/api/anthropic",
    defaultModel: "glm-5.1",
    modelMapping: {
      "gpt-4o": "glm-5.1",
      "gpt-4": "glm-5.1",
    },
    priority: 2,
    iconColor: "#0F62FE",
    apiKeyUrl: "https://z.ai/subscribe",
    models: ["glm-5.1"],
    apiFormat: "anthropic",
    websiteUrl: "https://z.ai",
    icon: "zhipu",
  },
  {
    name: "Baidu Qianfan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://qianfan.baidubce.com",
    defaultModel: "ernie-4.0-8k",
    modelMapping: {
      "gpt-4o": "ernie-4.0-8k",
      "gpt-4": "ernie-4.0-8k",
    },
    priority: 2,
    iconColor: "#2932E1",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    models: ["ernie-4.0-8k"],
    quotaStrategy: "webview",
    websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    icon: "baidu",
  },
  {
    name: "Baidu Qianfan Coding Plan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
    defaultModel: "qianfan-code-latest",
    modelMapping: {
      "gpt-4o": "qianfan-code-latest",
      "gpt-4": "qianfan-code-latest",
    },
    priority: 2,
    iconColor: "#2932E1",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    models: ["qianfan-code-latest"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://qianfan.baidubce.com/anthropic/coding"],
    websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    icon: "baidu",
  },
  {
    name: "Baidu Qianfan Token Plan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://qianfan.baidubce.com/anthropic/tokenplan/personal",
    defaultModel: "deepseek-v4-pro",
    modelMapping: {
      "gpt-4o": "deepseek-v4-pro",
      "gpt-4": "deepseek-v4-pro",
    },
    priority: 2,
    iconColor: "#2932E1",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/resource/token-plan",
    models: ["deepseek-v4-pro"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://qianfan.baidubce.com/anthropic/tokenplan/personal"],
    websiteUrl: "https://cloud.baidu.com/product/codingplan.html",
    icon: "baidu",
  },
  {
    name: "Bailian (Alibaba)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode",
    defaultModel: "qwen3-coder-plus",
    modelMapping: {
      "gpt-4o": "qwen3-coder-plus",
      "gpt-4": "qwen3-coder-plus",
      "claude-3-sonnet": "qwen3-coder-plus",
    },
    priority: 2,
    iconColor: "#624AFF",
    apiKeyUrl: "https://bailian.console.aliyun.com",
    models: ["qwen3-coder-plus", "qwen-max"],
    quotaStrategy: "webview",
    endpoints: {
      openai: "https://dashscope.aliyuncs.com/compatible-mode",
      anthropic: "https://dashscope.aliyuncs.com/apps/anthropic",
    },
    websiteUrl: "https://bailian.console.aliyun.com",
    icon: "bailian",
  },
  {
    name: "Bailian For Coding",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    defaultModel: "qwen3-coder-plus",
    modelMapping: {
      "gpt-4o": "qwen3-coder-plus",
      "gpt-4": "qwen3-coder-plus",
      "claude-3-sonnet": "qwen3-coder-plus",
    },
    priority: 2,
    iconColor: "#624AFF",
    apiKeyUrl: "https://bailian.console.aliyun.com",
    models: ["qwen3-coder-plus"],
    apiFormat: "anthropic",
    websiteUrl: "https://bailian.console.aliyun.com",
    icon: "bailian",
  },
  {
    name: "QwenCloud",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://dashscope-intl.aliyuncs.com/apps/anthropic",
    defaultModel: "qwen3.7-max",
    modelMapping: {
      "gpt-4o": "qwen3.7-max",
      "gpt-4": "qwen3.7-max",
      "claude-3-sonnet": "qwen3.7-max",
    },
    priority: 2,
    iconColor: "#6336E7",
    apiKeyUrl: "https://home.qwencloud.com/api-keys",
    models: ["qwen3.7-max", "qwen3.6-flash"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.qwencloud.com",
    icon: "qwen",
  },
  {
    name: "QwenCloud For Coding",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://coding-intl.dashscope.aliyuncs.com/apps/anthropic",
    defaultModel: "qwen3.7-plus",
    modelMapping: {
      "gpt-4o": "qwen3.7-plus",
      "gpt-4": "qwen3.7-plus",
      "claude-3-sonnet": "qwen3.7-plus",
    },
    priority: 2,
    iconColor: "#6336E7",
    apiKeyUrl: "https://home.qwencloud.com/api-keys",
    models: ["qwen3.7-plus"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.qwencloud.com",
    icon: "qwen",
  },
  {
    name: "QwenCloud Token Plan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/apps/anthropic",
    defaultModel: "qwen3.8-max",
    modelMapping: {
      "gpt-4o": "qwen3.8-max",
      "gpt-4": "qwen3.8-max",
      "claude-3-sonnet": "qwen3.8-max",
    },
    priority: 2,
    iconColor: "#6336E7",
    apiKeyUrl: "https://home.qwencloud.com/api-keys",
    models: ["qwen3.8-max", "qwen3.6-flash"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.qwencloud.com",
    icon: "qwen",
  },
  {
    name: "Kimi (Moonshot)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "kimi-k2.7-code",
    modelMapping: {
      "gpt-4o": "kimi-k2.7-code",
      "gpt-4": "kimi-k2.7-code",
    },
    priority: 2,
    iconColor: "#6366F1",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    models: ["kimi-k2.7-code", "kimi-k2.6"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://api.moonshot.cn/v1",
      anthropic: "https://api.moonshot.cn/anthropic",
    },
    websiteUrl: "https://platform.kimi.com",
    icon: "kimi",
  },
  {
    name: "Kimi For Coding",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.kimi.com/coding/",
    defaultModel: "kimi-for-coding",
    modelMapping: {
      "gpt-4o": "kimi-for-coding",
      "gpt-4": "kimi-for-coding",
      "claude-3-sonnet": "kimi-for-coding",
    },
    priority: 2,
    iconColor: "#6366F1",
    apiKeyUrl: "https://www.kimi.com/code/",
    models: ["kimi-for-coding"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.kimi.com/code/",
    icon: "kimi",
  },
  {
    name: "StepFun",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.stepfun.com/step_plan",
    defaultModel: "step-3.5-flash-2603",
    modelMapping: {
      "gpt-4o": "step-3.5-flash-2603",
      "gpt-4": "step-3.5-flash-2603",
    },
    priority: 2,
    iconColor: "#16D6D2",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    models: ["step-3.5-flash-2603"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://api.stepfun.com",
      anthropic: "https://api.stepfun.com/anthropic",
    },
    websiteUrl: "https://platform.stepfun.com/step-plan",
    endpointCandidates: ["https://api.stepfun.com/step_plan"],
    icon: "stepfun",
  },
  {
    name: "StepFun en",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.stepfun.ai/step_plan",
    defaultModel: "step-3.5-flash-2603",
    modelMapping: {
      "gpt-4o": "step-3.5-flash-2603",
      "gpt-4": "step-3.5-flash-2603",
    },
    priority: 2,
    iconColor: "#16D6D2",
    apiKeyUrl: "https://platform.stepfun.ai/interface-key",
    models: ["step-3.5-flash-2603"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://api.stepfun.ai/step_plan"],
    websiteUrl: "https://platform.stepfun.ai/step-plan",
    icon: "stepfun",
  },
  {
    name: "MiniMax",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.minimaxi.com",
    defaultModel: "MiniMax-M2.7",
    modelMapping: {
      "gpt-4o": "MiniMax-M2.7",
      "gpt-4": "MiniMax-M2.7",
    },
    priority: 2,
    iconColor: "#FF6B6B",
    apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
    models: ["MiniMax-M2.7"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://api.minimaxi.com",
      anthropic: "https://api.minimaxi.com/anthropic",
    },
    websiteUrl: "https://platform.minimaxi.com",
    icon: "minimax",
  },
  {
    name: "MiniMax en",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.minimax.io/anthropic",
    defaultModel: "MiniMax-M2.7",
    modelMapping: {
      "gpt-4o": "MiniMax-M2.7",
      "gpt-4": "MiniMax-M2.7",
    },
    priority: 2,
    iconColor: "#FF6B6B",
    apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
    models: ["MiniMax-M2.7"],
    apiFormat: "anthropic",
    websiteUrl: "https://platform.minimax.io",
    icon: "minimax",
  },
  {
    name: "DouBao (ByteDance)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    defaultModel: "ark-code-latest",
    modelMapping: {
      "gpt-4o": "ark-code-latest",
      "gpt-4": "ark-code-latest",
    },
    priority: 2,
    iconColor: "#3370FF",
    apiKeyUrl: "https://www.volcengine.com/product/doubao",
    models: ["ark-code-latest", "doubao-seed-2-0-code-preview-latest"],
    quotaStrategy: "webview",
    websiteUrl: "https://www.volcengine.com/product/doubao",
    icon: "huoshan",
  },
  {
    name: "火山 Agent Plan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan",
    defaultModel: "ark-code-latest",
    modelMapping: {
      "gpt-4o": "ark-code-latest",
      "gpt-4": "ark-code-latest",
    },
    priority: 2,
    iconColor: "#3370FF",
    apiKeyUrl: "https://www.volcengine.com/activity/agentplan",
    models: ["ark-code-latest"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.volcengine.com/activity/agentplan",
    icon: "huoshan",
  },
  {
    name: "火山 Coding Plan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    defaultModel: "ark-code-latest",
    modelMapping: {
      "gpt-4o": "ark-code-latest",
      "gpt-4": "ark-code-latest",
    },
    priority: 2,
    iconColor: "#3370FF",
    apiKeyUrl: "https://www.volcengine.com/activity/codingplan",
    models: ["ark-code-latest"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.volcengine.com/activity/codingplan",
    icon: "huoshan",
  },
  {
    name: "BytePlus",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
    defaultModel: "ark-code-latest",
    modelMapping: {
      "gpt-4o": "ark-code-latest",
      "gpt-4": "ark-code-latest",
    },
    priority: 2,
    iconColor: "#3370FF",
    apiKeyUrl: "https://www.byteplus.com/en/product/modelark",
    models: ["ark-code-latest"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.byteplus.com/en/product/modelark",
    icon: "huoshan",
  },
  {
    name: "BaiLing (Alipay)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.tbox.cn/api/anthropic",
    defaultModel: "Ling-2.5-1T",
    modelMapping: {
      "gpt-4o": "Ling-2.5-1T",
      "gpt-4": "Ling-2.5-1T",
    },
    priority: 2,
    iconColor: "#1677FF",
    models: ["Ling-2.5-1T"],
    quotaStrategy: "openai_compat",
    endpoints: {
      openai: "https://api.tbox.cn",
      anthropic: "https://api.tbox.cn/api/anthropic",
    },
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
  },
  {
    name: "Tencent Token Plan",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.lkeap.cloud.tencent.com/plan/anthropic",
    defaultModel: "tc-code-latest",
    modelMapping: {
      "gpt-4o": "tc-code-latest",
      "gpt-4": "tc-code-latest",
    },
    priority: 2,
    iconColor: "#0052D9",
    apiKeyUrl: "https://console.cloud.tencent.com/tokenhub/tokenplan",
    models: ["tc-code-latest"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://api.lkeap.cloud.tencent.com/plan/anthropic"],
    modelsUrl: "https://api.lkeap.cloud.tencent.com/plan/v3/models",
    websiteUrl: "https://cloud.tencent.com/product/tokenhub",
    icon: "tencent",
  },
  {
    name: "Tencent Token Plan (Intl)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic",
    defaultModel: "auto",
    modelMapping: {
      "gpt-4o": "auto",
      "gpt-4": "auto",
    },
    priority: 2,
    iconColor: "#0052D9",
    apiKeyUrl: "https://console.tencentcloud.com/tokenhub/tokenplan",
    models: ["auto"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic"],
    websiteUrl: "https://www.tencentcloud.com/products/tokenhub",
    icon: "tencent",
  },
  {
    name: "Tencent Token Plan Enterprise Pro",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://tokenhub.tencentmaas.com/plan/anthropic",
    defaultModel: "auto",
    modelMapping: {
      "gpt-4o": "auto",
      "gpt-4": "auto",
    },
    priority: 2,
    iconColor: "#0052D9",
    apiKeyUrl: "https://console.cloud.tencent.com/tokenhub/tokenplan-e",
    models: ["auto"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://tokenhub.tencentmaas.com/plan/anthropic", "https://tokenhub-intl.tencentmaas.com/plan/anthropic"],
    websiteUrl: "https://cloud.tencent.com/product/tokenhub",
    icon: "tencent",
  },
  {
    name: "Tencent Token Plan Enterprise Pro (Intl)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic",
    defaultModel: "auto",
    modelMapping: {
      "gpt-4o": "auto",
      "gpt-4": "auto",
    },
    priority: 2,
    iconColor: "#0052D9",
    apiKeyUrl: "https://console.tencentcloud.com/tokenhub/tokenplan-e",
    models: ["auto"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic", "https://tokenhub.tencentcloudmaas.com/plan/anthropic"],
    websiteUrl: "https://www.tencentcloud.com/products/tokenhub",
    icon: "tencent",
  },
  {
    name: "Tencent Token Plan Enterprise Lite",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://tokenhub.tencentmaas.com/plan/anthropic",
    defaultModel: "auto",
    modelMapping: {
      "gpt-4o": "auto",
      "gpt-4": "auto",
    },
    priority: 2,
    iconColor: "#0052D9",
    apiKeyUrl: "https://console.cloud.tencent.com/tokenhub/tokenplan-e",
    models: ["auto"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://tokenhub.tencentmaas.com/plan/anthropic", "https://tokenhub-intl.tencentmaas.com/plan/anthropic"],
    websiteUrl: "https://cloud.tencent.com/product/tokenhub",
    icon: "tencent",
  },
  {
    name: "Tencent Token Plan Enterprise Lite (Intl)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic",
    defaultModel: "auto",
    modelMapping: {
      "gpt-4o": "auto",
      "gpt-4": "auto",
    },
    priority: 2,
    iconColor: "#0052D9",
    apiKeyUrl: "https://console.tencentcloud.com/tokenhub/tokenplan-e",
    models: ["auto"],
    apiFormat: "anthropic",
    endpointCandidates: ["https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic", "https://tokenhub.tencentcloudmaas.com/plan/anthropic"],
    websiteUrl: "https://www.tencentcloud.com/products/tokenhub",
    icon: "tencent",
  },
  {
    name: "Xiaomi MiMo",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    defaultModel: "mimo-v2.5-pro",
    modelMapping: {
      "gpt-4o": "mimo-v2.5-pro",
      "gpt-4": "mimo-v2.5-pro",
    },
    priority: 2,
    iconColor: "#000000",
    models: ["mimo-v2.5-pro", "mimo-v2-pro"],
    quotaStrategy: "openai_compat",
    endpoints: {
      openai: "https://api.xiaomimimo.com",
      anthropic: "https://api.xiaomimimo.com/anthropic",
    },
    websiteUrl: "https://platform.xiaomimimo.com",
    icon: "xiaomimimo",
  },
  {
    name: "Xiaomi MiMo Token Plan (China)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
    defaultModel: "mimo-v2.5-pro",
    modelMapping: {
      "gpt-4o": "mimo-v2.5-pro",
      "gpt-4": "mimo-v2.5-pro",
    },
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/plan-manage",
    models: ["mimo-v2.5-pro"],
    apiFormat: "anthropic",
    websiteUrl: "https://platform.xiaomimimo.com/#/token-plan",
    icon: "xiaomimimo",
  },
  {
    name: "Longcat",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.longcat.chat/anthropic",
    defaultModel: "LongCat-Flash-Chat",
    modelMapping: {},
    priority: 2,
    iconColor: "#29E154",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    models: ["LongCat-Flash-Chat"],
    quotaStrategy: "openai_compat",
    endpoints: {
      openai: "https://api.longcat.chat",
      anthropic: "https://api.longcat.chat/anthropic",
    },
    websiteUrl: "https://longcat.chat",
  },
  {
    name: "KAT-Coder",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/${ENDPOINT_ID}/claude-code-proxy",
    defaultModel: "KAT-Coder-Pro V1",
    modelMapping: {
      "gpt-4o": "KAT-Coder-Pro V1",
      "gpt-4": "KAT-Coder-Pro V1",
    },
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://console.streamlake.ai/console/api-key",
    models: ["KAT-Coder-Pro V1", "KAT-Coder-Air V1"],
    apiFormat: "anthropic",
    websiteUrl: "https://console.streamlake.ai",
    icon: "catcoder",
    templateValues: {
      ENDPOINT_ID: {
        label: "Vanchin Endpoint ID",
        placeholder: "ep-xxx-xxx",
        defaultValue: "",
        editorValue: "",
      },
    },
  },

  // ─── Aggregators ───
  {
    name: "OpenRouter",
    category: "aggregator",
    provider: "openrouter",
    baseUrl: "https://openrouter.ai/api",
    defaultModel: "anthropic/claude-sonnet-4-20250514",
    modelMapping: {
      "gpt-4o": "openai/gpt-4o",
      "claude-3-sonnet": "anthropic/claude-sonnet-4-20250514",
    },
    priority: 2,
    iconColor: "#6D28D9",
    apiKeyUrl: "https://openrouter.ai/keys",
    models: [
      "anthropic/claude-sonnet-4-20250514",
      "anthropic/claude-opus-4-7",
      "anthropic/claude-haiku-4-5-20251001",
      "openai/gpt-4o",
      "openai/gpt-5.4",
      "google/gemini-3.1-pro",
    ],
    quotaStrategy: "http_api", // GET /api/v1/key
  },
  {
    name: "SiliconFlow",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://api.siliconflow.cn",
    defaultModel: "Pro/MiniMaxAI/MiniMax-M2.7",
    modelMapping: {
      "gpt-4o": "Pro/MiniMaxAI/MiniMax-M2.7",
      "gpt-4": "Pro/MiniMaxAI/MiniMax-M2.7",
    },
    priority: 2,
    iconColor: "#6E29F6",
    apiKeyUrl: "https://cloud.siliconflow.cn",
    models: ["Pro/MiniMaxAI/MiniMax-M2.7", "deepseek-ai/DeepSeek-V3"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://api.siliconflow.cn",
      anthropic: "https://api.siliconflow.cn/anthropic",
    },
    websiteUrl: "https://cloud.siliconflow.cn",
  },
  {
    name: "AiHubMix",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://aihubmix.com",
    defaultModel: "gpt-4o",
    modelMapping: {},
    priority: 2,
    iconColor: "#006FFB",
    apiKeyUrl: "https://aihubmix.com",
    models: ["gpt-4o", "claude-sonnet-4-6", "claude-opus-4-7"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://aihubmix.com",
    endpointCandidates: ["https://aihubmix.com", "https://api.aihubmix.com"],
    endpoints: {
      openai: "https://aihubmix.com",
      anthropic: "https://aihubmix.com",
    },
    icon: "aihubmix",
  },
  {
    name: "DMXAPI",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://www.dmxapi.cn",
    defaultModel: "gpt-4o",
    modelMapping: {},
    priority: 2,
    iconColor: "#3B82F6",
    apiKeyUrl: "https://www.dmxapi.cn",
    models: ["gpt-4o", "claude-sonnet-4-6", "claude-opus-4-7"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://www.dmxapi.cn",
    endpointCandidates: ["https://www.dmxapi.cn", "https://api.dmxapi.cn"],
    endpoints: {
      openai: "https://www.dmxapi.cn",
      anthropic: "https://www.dmxapi.cn",
    },
  },
  {
    name: "ModelScope",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://api-inference.modelscope.cn",
    defaultModel: "ZhipuAI/GLM-5",
    modelMapping: {
      "gpt-4o": "ZhipuAI/GLM-5",
      "gpt-4": "ZhipuAI/GLM-5",
    },
    priority: 2,
    iconColor: "#624AFF",
    models: ["ZhipuAI/GLM-5"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "TheRouter",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://api.therouter.ai",
    defaultModel: "anthropic/claude-sonnet-4-6",
    modelMapping: {
      "gpt-4o": "openai/gpt-5.4",
      "claude-3-sonnet": "anthropic/claude-sonnet-4-6",
    },
    priority: 2,
    iconColor: "#8B5CF6",
    models: [
      "anthropic/claude-sonnet-4-6",
      "anthropic/claude-opus-4-7",
      "openai/gpt-5.4",
      "google/gemini-3-flash-preview",
    ],
    quotaStrategy: "http_api", // credits API
  },
  {
    name: "Compshare",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://api.modelverse.cn",
    defaultModel: "gpt-4o",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    models: ["gpt-4o", "gpt-5.4"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    endpointCandidates: ["https://api.modelverse.cn"],
    icon: "ucloud",
  },
  {
    name: "Compshare Coding Plan",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://cp.compshare.cn",
    defaultModel: "claude-sonnet-4-6",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    models: ["claude-opus-4-7", "claude-sonnet-4-6"],
    apiFormat: "anthropic",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    endpointCandidates: ["https://cp.compshare.cn"],
    icon: "ucloud",
  },
  {
    name: "Shengsuanyun",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://router.shengsuanyun.com/api",
    defaultModel: "gpt-4o",
    modelMapping: {},
    priority: 2,
    iconColor: "#F59E0B",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "gpt-4o"],
    quotaStrategy: "http_api", // GET /api/v1/key
  },
  {
    name: "Novita AI",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://api.novita.ai",
    defaultModel: "deepseek/deepseek-r1",
    modelMapping: {},
    priority: 2,
    iconColor: "#10B981",
    apiKeyUrl: "https://novita.ai",
    models: ["deepseek/deepseek-r1", "zai-org/glm-5"],
    quotaStrategy: "http_api",
    endpoints: {
      openai: "https://api.novita.ai",
      anthropic: "https://api.novita.ai/anthropic",
    },
    websiteUrl: "https://novita.ai",
  },
  {
    name: "PIPELLM",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://cc-api.pipellm.ai",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#4F46E5",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "response_header",
  },
  {
    name: "Nvidia",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://integrate.api.nvidia.com",
    defaultModel: "moonshotai/kimi-k2.5",
    modelMapping: {
      "gpt-4o": "moonshotai/kimi-k2.5",
    },
    priority: 2,
    iconColor: "#76B900",
    models: ["moonshotai/kimi-k2.5"],
    quotaStrategy: "response_header", // no billing API
  },
  {
    name: "NewAPI",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://your-newapi-host.com",
    defaultModel: "claude-sonnet-4-6",
    modelMapping: {},
    priority: 2,
    iconColor: "#6B7280",
    models: ["claude-sonnet-4-6", "gpt-4o", "gemini-3.1-pro"],
    quotaStrategy: "openai_compat",
  },

  // ─── Cloud Providers ───
  {
    name: "Azure OpenAI",
    category: "cloud_provider",
    provider: "openai",
    baseUrl: "https://YOUR_RESOURCE.openai.azure.com",
    defaultModel: "gpt-4o",
    modelMapping: {},
    priority: 3,
    iconColor: "#0078D4",
    apiKeyUrl: "https://oai.azure.com",
    models: ["gpt-4o", "gpt-4o-mini", "o3"],
    quotaStrategy: "response_header",
  },
  {
    name: "AWS Bedrock (AKSK)",
    category: "cloud_provider",
    provider: "anthropic",
    baseUrl: "https://bedrock-runtime.us-west-2.amazonaws.com",
    defaultModel: "global.anthropic.claude-opus-5",
    modelMapping: {},
    priority: 3,
    iconColor: "#FF9900",
    models: ["global.anthropic.claude-opus-5", "global.anthropic.claude-sonnet-5", "global.anthropic.claude-haiku-4-5-20251001-v1:0"],
    quotaStrategy: "disabled",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    icon: "aws",
    templateValues: {
      AWS_REGION: {
        label: "AWS Region",
        placeholder: "us-west-2",
        defaultValue: "us-west-2",
        editorValue: "us-west-2",
      },
      AWS_ACCESS_KEY_ID: {
        label: "Access Key ID",
        placeholder: "AKIA...",
        defaultValue: "",
        editorValue: "",
      },
      AWS_SECRET_ACCESS_KEY: {
        label: "Secret Access Key",
        placeholder: "your-secret-key",
        defaultValue: "",
        editorValue: "",
      },
    },
  },
  {
    name: "AWS Bedrock (API Key)",
    category: "cloud_provider",
    provider: "anthropic",
    baseUrl: "https://bedrock-runtime.us-west-2.amazonaws.com",
    defaultModel: "global.anthropic.claude-opus-5",
    modelMapping: {},
    priority: 3,
    iconColor: "#FF9900",
    models: ["global.anthropic.claude-opus-5", "global.anthropic.claude-sonnet-5", "global.anthropic.claude-haiku-4-5-20251001-v1:0"],
    quotaStrategy: "disabled",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    icon: "aws",
    templateValues: {
      AWS_REGION: {
        label: "AWS Region",
        placeholder: "us-west-2",
        defaultValue: "us-west-2",
        editorValue: "us-west-2",
      },
    },
  },
  {
    name: "Google Gemini",
    category: "cloud_provider",
    provider: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com",
    defaultModel: "gemini-2.5-pro",
    modelMapping: {
      "gpt-4o": "gemini-2.5-pro",
      "gpt-4": "gemini-2.5-pro",
    },
    priority: 3,
    iconColor: "#4285F4",
    apiKeyUrl: "https://aistudio.google.com/app/apikey",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-3.1-pro"],
    apiFormat: "gemini",
    quotaStrategy: "response_header", // no billing API, only usageMetadata
  },

  // ─── Third-party Relay ───
  // All third-party relays typically use NewAPI/OneAPI and support openai_compat billing
  {
    name: "PackyCode",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://www.packyapi.com",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#6366F1",
    apiKeyUrl: "https://www.packyapi.com",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "Cubence",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://api.cubence.com",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://cubence.com/signup",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://cubence.com",
    endpointCandidates: ["https://api.cubence.com", "https://api-cf.cubence.com", "https://api-dmit.cubence.com", "https://api-bwg.cubence.com"],
    icon: "cubence",
  },
  {
    name: "AIGoCode",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://api.aigocode.app",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#5B7FFF",
    apiKeyUrl: "https://aigocode.app/invite",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://aigocode.app",
    endpointCandidates: ["https://api.aigocode.app"],
    icon: "aigocode",
  },
  {
    name: "RightCode",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://www.right.codes/claude",
    defaultModel: "claude-sonnet-4-6",
    modelMapping: {},
    priority: 2,
    iconColor: "#E96B2C",
    models: ["claude-sonnet-4-6", "claude-opus-4-7"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "AICodeMirror",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://api.aicodemirror.ai/api/claudecode",
    defaultModel: "claude-sonnet-4-6",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://www.aicodemirror.ai/register",
    models: ["claude-opus-4-7", "claude-sonnet-4-6"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://www.aicodemirror.ai",
    endpointCandidates: ["https://api.aicodemirror.ai/api/claudecode"],
    icon: "aicodemirror",
  },
  {
    name: "AICoding",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://api.aicoding.inc",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://aicoding.inc/i",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://aicoding.inc",
    endpointCandidates: ["https://api.aicoding.inc"],
    icon: "aicoding",
  },
  {
    name: "CrazyRouter",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://cn.crazyrouter.com",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://www.crazyrouter.com/register",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
    websiteUrl: "https://www.crazyrouter.com",
    endpointCandidates: ["https://cn.crazyrouter.com"],
    icon: "crazyrouter",
  },
  {
    name: "SSSAiCode",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://node-hk.sssaicode.com/api",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#7C3AED",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
  },
  {
    name: "Micu",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://www.openclaudecode.cn",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#06B6D4",
    models: ["claude-opus-4-7", "claude-sonnet-4-6"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "CTok.ai",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://api.ctok.ai",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#F97316",
    models: ["claude-opus-4-7", "claude-sonnet-4-6"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "DDSHub",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://www.ddshub.cc",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#EF4444",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "E-FlowCode",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://e-flowcode.cc",
    defaultModel: "gpt-5.4",
    modelMapping: {},
    priority: 2,
    iconColor: "#22C55E",
    models: ["gpt-5.4", "gpt-5.3-codex", "gpt-5.2"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "LionCCAPI",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://vibecodingapi.ai",
    defaultModel: "claude-opus-4-7",
    modelMapping: {},
    priority: 2,
    iconColor: "#A855F7",
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-sonnet-4-20250514", "claude-haiku-4-5-20251001"],
    quotaStrategy: "openai_compat",
  },
  {
    name: "LemonData",
    category: "third_party",
    provider: "custom",
    baseUrl: "https://api.lemondata.cc",
    defaultModel: "gpt-5.4",
    modelMapping: {},
    priority: 2,
    iconColor: "#FACC15",
    models: ["gpt-5.4"],
    quotaStrategy: "openai_compat",
  },

  // ─── International Official ───
  {
    name: "Mistral AI",
    category: "official",
    provider: "custom",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    modelMapping: {},
    priority: 2,
    iconColor: "#FF5000",
    apiKeyUrl: "https://console.mistral.ai/api-keys",
    models: ["mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "open-mistral-7b", "open-mixtral-8x7b", "open-mixtral-8x22b"],
    quotaStrategy: "response_header",
  },
  {
    name: "Groq",
    category: "official",
    provider: "custom",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    modelMapping: {},
    priority: 2,
    iconColor: "#F55036",
    apiKeyUrl: "https://console.groq.com/keys",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768", "gemma2-9b-it"],
    quotaStrategy: "response_header",
  },
  {
    name: "Together AI",
    category: "aggregator",
    provider: "custom",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    modelMapping: {},
    priority: 2,
    iconColor: "#0F6FFF",
    apiKeyUrl: "https://api.together.ai/settings/api-keys",
    models: ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo", "Qwen/Qwen2.5-72B-Instruct-Turbo"],
    quotaStrategy: "http_api",
  },
  {
    name: "Cohere",
    category: "official",
    provider: "custom",
    baseUrl: "https://api.cohere.ai/v1",
    defaultModel: "command-r-plus",
    modelMapping: {},
    priority: 2,
    iconColor: "#39594D",
    apiKeyUrl: "https://dashboard.cohere.com/api-keys",
    models: ["command-r-plus", "command-r", "command", "command-light"],
    quotaStrategy: "response_header",
  },
  {
    name: "xAI (Grok)",
    category: "official",
    provider: "custom",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-beta",
    modelMapping: {},
    priority: 2,
    iconColor: "#000000",
    apiKeyUrl: "https://console.x.ai",
    models: ["grok-beta", "grok-vision-beta", "grok-2", "grok-2-vision"],
    quotaStrategy: "response_header",
  },
  {
    name: "Yi (01.AI)",
    category: "cn_official",
    provider: "custom",
    baseUrl: "https://api.01.ai/v1",
    defaultModel: "yi-large",
    modelMapping: {},
    priority: 2,
    iconColor: "#00A6FB",
    apiKeyUrl: "https://platform.01.ai",
    models: ["yi-large", "yi-medium", "yi-small", "yi-large-turbo"],
    quotaStrategy: "response_header",
  },
];

/** Group presets by category for the UI */
export function groupPresetsByCategory(): Record<PresetCategory, ProviderPreset[]> {
  const groups: Record<PresetCategory, ProviderPreset[]> = {
    official: [],
    cn_official: [],
    aggregator: [],
    cloud_provider: [],
    third_party: [],
  };
  for (const preset of PROVIDER_PRESETS) {
    groups[preset.category].push(preset);
  }
  return groups;
}
